name: moveseg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - movement
  - napari
  - pyqt
  - numpy
  - xarray
  - pip
  - pip:
      - audioio
      - thunderhopper
      - pyqtgraph
      - napari-pyav @ https://github.com/horsto/napari-pyav/releases/download/v0.0.10.1/napari_pyav-0.0.10-py3-none-any.whl
      - -e .
