name: ethograph
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - movement
  - napari
  - pyqt
  - numpy
  - xarray
  - netcdf4
  # PyTorch with CUDA 12.1
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - scikit-learn
  - tqdm
  # Config
  - pyyaml
  - menuinst
  - pip
  - pip:
      - omegaconf
