name: ethograph
channels:
  - conda-forge
dependencies:
  - python=3.11
  - movement
  - napari
  - pyqt
  - numpy
  - xarray
  - netcdf4
  - menuinst
  - pip
  - pip:
      - audioio
      - ruptures
      - noisereduce
      - git+https://github.com/timsainb/vocalization-segmentation.git
      - git+https://github.com/Akseli-Ilmanen/vocalpy.git
      - librosa
      - pyqtgraph
      - napari-pyav @ https://github.com/horsto/napari-pyav/releases/download/v0.0.10.1/napari_pyav-0.0.10-py3-none-any.whl
      - -e .
