fps_playback: 30.0
spec_colormap: CET-R4
vmax_db: -20.0
vmin_db: -120.0
audio_cp_min_syllable_length_s: 0.02
noise_reduce_enabled: false
percentile_ylim: 99.5
show_changepoints: true
import_labels_nc_data: false
noise_reduce_prop_decrease: 1.0
video_path: D:\Alice\VidData\20250514_01_Ivy\2025-05-14_072_Ivy-cam-1.mp4
downsample_factor: 100
space_plot_type: Layer controls
all_checkbox_states:
  space: true
hop_frac: 0.5
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250514_01/behav/Trial_data.nc
window_size: 3.0
audio_cp_hop_length_ms: 5.0
nfft: 256
audio_cp_silence_threshold: 0.1
downsample_enabled: false
audio_channel_idx: 0
video_folder: D:/Alice/VidData/20250514_01_Ivy
buffer_multiplier: 5.0
audio_cp_min_level_db: -70.0
cameras_sel: cam1_file
colors_sel: None
features_sel: aux_acceleration_1000Hz
features_sel_previous: aux_velocity_1000Hz
individuals_sel: Ivy
keypoints_sel: beakTip
s3d_dims_sel: '0'
trials_sel: 72
