nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/20210119_Recording_SR1_SR2_social_vidtwo/pair24.nc
fps_playback: 30.0
recompute_threshold: 0.5
plot_spectrogram: false
import_labels_nc_data: false
percentile_ylim: 99.5
video_buffer_size: 300
window_size: 5.0
video_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/20210119_Recording_SR1_SR2_social_vidtwo/videos
vmin_db: -120.0
cmap: magma
nfft: 1024
hop_frac: 0.5
vmax_db: 20.0
space_plot_type: Layer controls
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\20210119_Recording_SR1_SR2_social_vidtwo\videos\Camera1\14000.mp4
buffer_multiplier: 5.0
cameras_sel: cam1
features_sel: speed
features_sel_previous: velocity
individuals_sel: an1
keypoints_sel: HeadF
trial_conditions_sel: None
trials_sel: '4'
