nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250504_01/behav/Trial_data.nc
noise_reduce_prop_decrease: 1.0
show_changepoints: true
downsample_enabled: false
all_checkbox_states:
  space: true
percentile_ylim: 99.5
spec_colormap: CET-R4
noise_reduce_enabled: false
vmax_db: -20.0
vmin_db: -120.0
fps_playback: 10.0
video_path: D:\Alice\VidData\20250504_01_Ivy\2025-05-04_062_Ivy-cam-1.mp4
buffer_multiplier: 5.0
video_folder: D:/Alice/VidData/20250504_01_Ivy
audio_cp_min_level_db: -70.0
window_size: 3.0
audio_channel_idx: 0
audio_cp_silence_threshold: 0.1
downsample_factor: 100
import_labels_nc_data: false
nfft: 256
space_plot_type: Layer controls
hop_frac: 0.5
audio_cp_hop_length_ms: 5.0
audio_cp_min_syllable_length_s: 0.02
cameras_sel: cam1
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: aux_speed
individuals_sel: Ivy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
s3d_dims_sel: '0'
trials_sel: 62
