vmax_db: -33.1
spec_ymax: 22000000.0
window_size: 30.0
plot_spectrogram: false
nfft: 256
space_plot_type: Layer controls
ymin: 0.0
hop_frac: 0.5
percentile_ylim: 99.5
vmin_db: -100.0
audio_folder: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\BP_2021-05-25_08-12-51_655154_0380000.wav
spec_buffer: 1.0
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/copExpBP08/x.nc
spec_ymin: 0.0
spec_colormap: CET-R4
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\BP_2021-05-25_08-12-51_655154_0380000.mp4
buffer_multiplier: 5.0
fps_playback: 30.0
ymax: 0.005
import_labels_nc_data: false
video_folder: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08
cameras_sel: cam1
features_sel: Spectrogram
features_sel_previous: envelope
individuals_sel: male
mics_sel: mic1
trial_conditions_sel: None
trials_sel: sample_trial
