plot_spectrogram: false
percentile_ylim: 99.5
fps_playback: 30.0
space_plot_type: space_3D
spec_colormap: CET-R4
hop_frac: 0.5
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250309_01_Ivy\2025-03-09_068_Ivy-cam-1.mp4
window_size: 3.0
vmin_db: -120.0
buffer_multiplier: 5.0
import_labels_nc_data: false
nfft: 256
nc_file_path: C:/Users/Admin/Desktop/Ivy_label/ses-000_date-20250309_01/behav/Trial_data.nc
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250309_01_Ivy
vmax_db: -20.0
audio_channel_idx: 0
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 68
