fps_playback: 30.0
audio_cp_silence_threshold: 0.1
buffer_multiplier: 5.0
noise_reduce_enabled: false
audio_channel_idx: 0
vmin_db: -120.0
video_path: C:\Users\aksel\Desktop\FreddyTrain\20250527_01_Freddy\2025-05-27_001_Freddy-cam-1.mp4
nc_file_path: C:/Users/aksel/Desktop/FreddyTrain/Trial_data2701.nc
audio_cp_min_syllable_length_s: 0.02
video_folder: C:/Users/aksel/Desktop/FreddyTrain/20250527_01_Freddy
vmax_db: -20.0
hop_frac: 0.5
import_labels_nc_data: false
spec_colormap: CET-R4
noise_reduce_prop_decrease: 1.0
space_plot_type: Layer controls
downsample_factor: 100
show_changepoints: true
downsample_enabled: false
nfft: 256
percentile_ylim: 99.5
audio_cp_hop_length_ms: 5.0
window_size: 3.0
audio_cp_min_level_db: -70.0
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: position
individuals_sel: Freddy
keypoints_sel: beakTip
s3d_dims_sel: '0'
space_sel: x
trials_sel: 1
