hop_frac: 0.5
ymin: 0.0
vmax_db: -20.0
nc_file_path: C:/Users/Admin/Desktop/Ivy_label/ses-000_date-20250306_01/behav/Trial_data.nc
ymax: 70.0
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250306_01_Ivy\2025-03-06_054_Ivy-cam-1.mp4
fps_playback: 30.0
vmin_db: -120.0
buffer_multiplier: 5.0
percentile_ylim: 99.5
audio_channel_idx: 0
space_plot_type: space_3D
import_labels_nc_data: false
spec_colormap: CET-R4
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250306_01_Ivy
plot_spectrogram: false
nfft: 256
window_size: 3.0
audio_folder: ''
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
trial_conditions_sel: None
trials_sel: 54
