buffer_multiplier: 5.0
percentile_ylim: 99.5
space_plot_type: Layer controls
vmin_db: -120.0
vmax_db: 20.0
nc_file_path: C:/Users/aksel/Desktop/FreddyTrain/Trial_data2701.nc
recompute_threshold: 0.5
video_path: C:\Users\aksel\Desktop\FreddyTrain\20250527_01_Freddy\2025-05-27_007_Freddy-cam-1.mp4
hop_frac: 0.5
import_labels_nc_data: true
fps_playback: 30.0
video_folder: C:/Users/aksel/Desktop/FreddyTrain/20250527_01_Freddy
video_buffer_size: 300
cmap: magma
plot_spectrogram: false
nfft: 1024
window_size: 5.0
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: position
individuals_sel: Freddy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 7
