vmax_db: 20.0
space_plot_type: Layer controls
fps_playback: 30.0
video_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Night_of_the_Living_Dead
hop_frac: 0.5
recompute_threshold: 0.5
audio_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Night_of_the_Living_Dead
import_labels_nc_data: false
vmin_db: -120.0
window_size: 5.0
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/Night_of_the_Living_Dead/Movie_noTP.nc
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Night_of_the_Living_Dead\movie.wav
buffer_multiplier: 5.0
percentile_ylim: 99.5
plot_spectrogram: false
video_buffer_size: 300
cmap: magma
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Night_of_the_Living_Dead\movie.mp4
nfft: 1024
cameras_sel: cam1
features_sel: envelope
individuals_sel: Ben
mics_sel: mic1
trial_conditions_sel: None
trials_sel: 1
