spec_colormap: CET-L8
plot_spectrogram: false
vmin_db: -100.0
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/copExpBP08/x.nc
buffer_multiplier: 5.0
audio_folder: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08
nfft: 256
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\BP_2021-05-25_08-12-51_655154_0380000.wav
spec_ymin: 0.0
window_size: 3.0
import_labels_nc_data: false
ymin: 0.0
space_plot_type: Layer controls
percentile_ylim: 99.5
vmax_db: -31.9
video_folder: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08
fps_playback: 30.0
ymax: 0.0
hop_frac: 0.5
spec_ymax: 2000000.0
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\BP_2021-05-25_08-12-51_655154_0380000.mp4
cameras_sel: cam1
features_sel: envelope
features_sel_previous: Waveform
individuals_sel: male
mics_sel: mic1
trial_conditions_sel: None
trials_sel: sample_trial
