percentile_ylim: 99.5
fps_playback: 30.0
vmax_db: -20.0
downsample_factor: 100
buffer_multiplier: 5.0
window_size: 3.0
nfft: 256
audio_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/copExpBP08
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/copExpBP08/birdpark_accelerometer.nc
video_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/copExpBP08
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\audio.wav
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\video.mp4
audio_channel_idx: 0
space_plot_type: Layer controls
hop_frac: 0.5
spec_colormap: CET-R4
vmin_db: -120.0
downsample_enabled: true
import_labels_nc_data: false
cameras_sel: cam1
features_sel: vibration (accelerometer)
individuals_sel: male (red radio)
mics_sel: mic1
mics_sel_previous: mic1 (Ch 4)
trials_sel: sample_trial
