nfft: 256
nc_file_path: C:/Users/Admin/Desktop/Ivy_label/ses-000_date-20250306_01/behav/Trial_data.nc
vmax_db: -20.0
ymax: 70.0
spec_colormap: CET-R4
window_size: 2.5
buffer_multiplier: 5.0
hop_frac: 0.5
import_labels_nc_data: false
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250306_01_Ivy
vmin_db: -120.0
space_plot_type: space_3D
fps_playback: 30.0
ymin: 0.0
plot_spectrogram: false
audio_channel_idx: 0
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250306_01_Ivy\2025-03-06_043_Ivy-cam-1.mp4
percentile_ylim: 99.5
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 43
