window_size: 3.0
vmin_db: -120.0
video_folder: D:/Alice/VidData/20250504_01_Ivy
buffer_multiplier: 5.0
fps_playback: 30.0
video_path: D:\Alice\VidData\20250504_01_Ivy\2025-05-04_005_Ivy-cam-1.mp4
audio_cp_min_syllable_length_s: 0.02
show_changepoints: true
noise_reduce_prop_decrease: 1.0
downsample_enabled: false
spec_colormap: CET-R4
nfft: 256
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250504_01/behav/Trial_data.nc
import_labels_nc_data: false
all_checkbox_states:
  space: true
audio_channel_idx: 0
vmax_db: -20.0
audio_cp_min_level_db: -70.0
hop_frac: 0.5
downsample_factor: 100
audio_cp_hop_length_ms: 5.0
percentile_ylim: 99.5
space_plot_type: Layer controls
audio_cp_silence_threshold: 0.1
noise_reduce_enabled: false
cameras_sel: cam1
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
keypoints_sel: beakTip
s3d_dims_sel: '0'
trials_sel: 5
