fps_playback: 30.0
video_folder: D:/Alice/VidData/20250513_01_Ivy
vmin_db: -120.0
video_path: D:\Alice\VidData\20250513_01_Ivy\2025-05-13_091_Ivy-cam-1.mp4
show_changepoints: true
hop_frac: 0.5
buffer_multiplier: 5.0
audio_channel_idx: 0
window_size: 15.0
vmax_db: -20.0
downsample_enabled: false
spec_colormap: CET-R4
import_labels_nc_data: false
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250513_01/behav/Trial_data.nc
noise_reduce_enabled: false
downsample_factor: 100
noise_reduce_prop_decrease: 1.0
space_plot_type: space_3D
audio_cp_silence_threshold: 0.1
all_checkbox_states:
  space: true
audio_cp_min_level_db: -70.0
nfft: 256
percentile_ylim: 99.5
audio_cp_hop_length_ms: 5.0
audio_cp_min_syllable_length_s: 0.02
cameras_sel: cam1
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
s3d_dims_sel: '0'
trial_conditions_sel: None
trials_sel: 91
