plot_spectrogram: false
vmax_db: 20.0
window_size: 5.0
recompute_threshold: 0.5
fps_playback: 30.0
cmap: magma
nfft: 1024
hop_frac: 0.5
video_buffer_size: 300
buffer_multiplier: 5.0
nc_file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
vmin_db: -120.0
import_labels_nc_data: false
space_plot_type: Layer controls
percentile_ylim: 99.5
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250527_01_Freddy\2025-05-27_001_Freddy-cam-1.mp4
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: position
individuals_sel: Freddy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
