audio_channel_idx: 0
video_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera
hop_frac: 0.5
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera/Philodoptera_labelsr1000.nc
spec_colormap: CET-R4
plot_spectrogram: false
nfft: 256
buffer_multiplier: 5.0
tracking_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera
vmin_db: -120.0
window_size: 5.0
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Philodoptera\audio.wav
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Philodoptera\video.mp4
audio_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera
vmax_db: -20.0
space_plot_type: Layer controls
fps_playback: 30.0
percentile_ylim: 99.5
import_labels_nc_data: false
cameras_sel: cam1
features_sel: speed
features_sel_previous: velocity
individuals_sel: Pholidoptera_littoralis_1
individuals_sel_previous: individual_0
keypoints_sel: LeftWingTip
mics_sel: mic1
tracking_sel: dlc1
trial_conditions_sel: None
trials_sel: sample_trial
