audio_cp_min_level_db: -70.0
vmax_db: -20.0
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250514_01_Ivy
downsample_enabled: false
noise_reduce_prop_decrease: 1.0
buffer_multiplier: 5.0
audio_cp_silence_threshold: 0.1
hop_frac: 0.5
import_labels_nc_data: false
downsample_factor: 100
nc_file_path: C:/Users/Admin/Desktop/Ivy_label/ses-000_date-20250514_01/behav/Trial_data.nc
space_plot_type: space_3D
nfft: 256
show_changepoints: true
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250514_01_Ivy\2025-05-14_089_Ivy-cam-1.mp4
fps_playback: 60.0
vmin_db: -120.0
percentile_ylim: 99.5
ymin: 0.0
audio_cp_hop_length_ms: 5.0
window_size: 3.0
noise_reduce_enabled: false
ymax: 70.0
spec_colormap: CET-R4
audio_channel_idx: 0
audio_cp_min_syllable_length_s: 0.02
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
s3d_dims_sel: '0'
trials_sel: 89
