window_size: 3.0
audio_channel_idx: 0
nfft: 256
tracking_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera
vmin_db: -120.0
video_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera
audio_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera
fps_playback: 1.0
buffer_multiplier: 5.0
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/Philodoptera/Philodoptera_labelsr1000.nc
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Philodoptera\video.mp4
spec_colormap: CET-R4
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Philodoptera\audio.wav
plot_spectrogram: false
percentile_ylim: 99.5
vmax_db: -20.0
space_plot_type: Layer controls
import_labels_nc_data: false
hop_frac: 0.5
cameras_sel: cam1
features_sel: position
individuals_sel: Pholidoptera_littoralis_1
keypoints_sel: LeftWingTip
mics_sel: mic1
space_sel: x
tracking_sel: dlc1
trials_sel: sample_trial
