plot_spectrogram: false
buffer_multiplier: 5.0
video_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Night_of_the_Living_Dead
fps_playback: 30.0
import_labels_nc_data: false
percentile_ylim: 99.5
recompute_threshold: 0.5
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Night_of_the_Living_Dead\movie.mp4
video_buffer_size: 300
hop_frac: 0.5
window_size: 5.0
audio_folder: C:/Users/aksel/Documents/Code/EthoGraph/data/Night_of_the_Living_Dead
vmin_db: -120.0
space_plot_type: Layer controls
vmax_db: 20.0
cmap: magma
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\Night_of_the_Living_Dead\movie.wav
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/Night_of_the_Living_Dead/MovieString.nc
nfft: 1024
cameras_sel: cam1
features_sel: envelope
individuals_sel: Ben
mics_sel: mic1
trial_conditions_sel: None
trials_sel: movie1
