vmax_db: 20.0
audio_path: C:\Users\aksel\Documents\Code\MoveSeg\data\Night_of_the_Living_Dead\movie.wav
nc_file_path: C:/Users/aksel/Documents/Code/MoveSeg/data/Night_of_the_Living_Dead/Movie_noTP.nc
fps_playback: 30.0
recompute_threshold: 0.5
video_folder: C:/Users/aksel/Documents/Code/MoveSeg/data/Night_of_the_Living_Dead
video_buffer_size: 300
hop_frac: 0.5
audio_folder: C:/Users/aksel/Documents/Code/MoveSeg/data/Night_of_the_Living_Dead
plot_spectrogram: false
vmin_db: -120.0
buffer_multiplier: 5.0
space_plot_type: Layer controls
percentile_ylim: 99.5
window_size: 5.0
nfft: 1024
import_labels_nc_data: false
cmap: magma
video_path: C:\Users\aksel\Documents\Code\MoveSeg\data\Night_of_the_Living_Dead\movie.mp4
cameras_sel: cam1
features_sel: envelope
individuals_sel: Ben
mics_sel: mic1
trial_conditions_sel: None
trials_sel: 1
