video_buffer_size: 300
vmin_db: -120.0
nfft: 1024
percentile_ylim: 99.5
window_size: 5.0
recompute_threshold: 0.5
buffer_multiplier: 5.0
cmap: magma
fps_playback: 30.0
nc_file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
plot_spectrogram: false
space_plot_type: Layer controls
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
vmax_db: 20.0
import_labels_nc_data: false
hop_frac: 0.5
