space_plot_type: Layer controls
window_size: 5.0
import_labels_nc_data: true
vmax_db: -20.0
percentile_ylim: 99.5
buffer_multiplier: 5.0
hop_frac: 0.5
plot_spectrogram: false
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
audio_channel_idx: 0
vmin_db: -120.0
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250527_01_Freddy\2025-05-27_012_Freddy-cam-1.mp4
nc_file_path: C:/Users/Admin/Desktop/trainFreddy/Trial_data2701.nc
fps_playback: 30.0
spec_colormap: CET-R4
nfft: 256
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: position
individuals_sel: Freddy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 12
