spec_colormap: CET-R4
nfft: 256
audio_cp_hop_length_ms: 5.0
percentile_ylim: 99.5
audio_cp_silence_threshold: 0.1
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250514_01/behav/Trial_data.nc
hop_frac: 0.5
buffer_multiplier: 5.0
audio_channel_idx: 0
space_plot_type: Layer controls
show_changepoints: true
audio_cp_min_syllable_length_s: 0.02
vmax_db: -20.0
audio_cp_min_level_db: -70.0
vmin_db: -120.0
window_size: 3.0
noise_reduce_enabled: false
noise_reduce_prop_decrease: 1.0
downsample_factor: 100
video_path: D:\Alice\VidData\20250514_01_Ivy\2025-05-14_001_Ivy-cam-1.mp4
fps_playback: 30.0
video_folder: D:/Alice/VidData/20250514_01_Ivy
downsample_enabled: false
import_labels_nc_data: false
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: position
individuals_sel: Ivy
keypoints_sel: beakTip
s3d_dims_sel: '0'
space_sel: x
trials_sel: 1
