ymax: 0.005
vmax_db: -31.6
plot_spectrogram: false
nfft: 120
space_plot_type: Layer controls
video_folder: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08
spec_ymin: 0.0
audio_folder: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08
spec_ymax: 15000.0
vmin_db: -100.0
buffer_multiplier: 5.0
spec_colormap: CET-R4
audio_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\BP_2021-05-25_08-12-51_655154_0380000.wav
fps_playback: 30.0
video_path: C:\Users\aksel\Documents\Code\EthoGraph\data\copExpBP08\BP_2021-05-25_08-12-51_655154_0380000.mp4
hop_frac: 0.3
import_labels_nc_data: false
nc_file_path: C:/Users/aksel/Documents/Code/EthoGraph/data/copExpBP08/x.nc
window_size: 4.0
percentile_ylim: 99.5
ymin: 0.0
cameras_sel: cam1
features_sel: Spectrogram
features_sel_previous: Waveform
individuals_sel: male
mics_sel: mic1
trial_conditions_sel: None
trials_sel: sample_trial
