all_checkbox_states:
  space: true
buffer_multiplier: 5.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250507_03/behav/Trial_data.nc
spec_colormap: CET-R4
hop_frac: 0.5
audio_channel_idx: 0
downsample_factor: 100
space_plot_type: space_3D
audio_cp_min_level_db: -70.0
audio_cp_silence_threshold: 0.1
video_path: D:\Alice\VidData\20250507_03_Ivy\2025-05-07_112_Ivy-cam-1.mp4
video_folder: D:/Alice/VidData/20250507_03_Ivy
nfft: 256
window_size: 7.0
percentile_ylim: 99.5
show_changepoints: true
downsample_enabled: false
noise_reduce_prop_decrease: 1.0
vmax_db: -20.0
fps_playback: 30.0
noise_reduce_enabled: false
import_labels_nc_data: false
audio_cp_min_syllable_length_s: 0.02
audio_cp_hop_length_ms: 5.0
vmin_db: -120.0
cameras_sel: cam1
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: aux_velocity
individuals_sel: Ivy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
s3d_dims_sel: '0'
trials_sel: 112
