plot_spectrogram: false
vmax_db: 20.0
space_plot_type: Layer controls
fps_playback: 30.0
hop_frac: 0.5
window_size: 5.0
recompute_threshold: 0.5
vmin_db: -120.0
video_buffer_size: 300
buffer_multiplier: 5.0
nfft: 1024
import_labels_nc_data: false
cmap: magma
percentile_ylim: 99.5
