vmin_db: -120.0
hop_frac: 0.5
fps_playback: 30.0
buffer_multiplier: 5.0
nfft: 256
vmax_db: -20.0
percentile_ylim: 99.5
apply_changepoint_correction: true
all_checkbox_states:
  space: true
video_folder: D:/Alice/VidData/20250519_01_Ivy
downsample_enabled: false
window_size: 15.0
audio_channel_idx: 0
noise_reduce_prop_decrease: 1.0
audio_cp_min_level_db: -70.0
noise_reduce_enabled: false
audio_cp_silence_threshold: 0.1
import_labels_nc_data: false
space_plot_type: Layer controls
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250519_01/behav/Trial_data.nc
audio_cp_min_syllable_length_s: 0.02
spec_colormap: CET-R4
video_path: D:\Alice\VidData\20250519_01_Ivy\2025-05-19_083_Ivy-cam-1.mp4
audio_cp_hop_length_ms: 5.0
show_changepoints: true
downsample_factor: 100
cameras_sel: cam1
cameras_sel_previous: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
individuals_sel_previous: Freddy
keypoints_sel: beakTip
s3d_dims_sel: '0'
trials_sel: 83
