import_labels_nc_data: false
vmax_db: -20.0
nfft: 256
show_changepoints: true
nc_file_path: C:/Users/aksel/Desktop/FreddyTrain/Trial_data2701.nc
video_folder: C:/Users/aksel/Desktop/FreddyTrain/20250527_01_Freddy
hop_frac: 0.5
vmin_db: -120.0
video_path: C:\Users\aksel\Desktop\FreddyTrain\20250527_01_Freddy\2025-05-27_047_Freddy-cam-1.mp4
noise_reduce_enabled: false
audio_cp_hop_length_ms: 5.0
space_plot_type: Layer controls
audio_channel_idx: 0
window_size: 3.0
fps_playback: 30.0
audio_cp_silence_threshold: 0.1
spec_colormap: CET-R4
buffer_multiplier: 5.0
downsample_factor: 100
noise_reduce_prop_decrease: 1.0
percentile_ylim: 99.5
downsample_enabled: false
audio_cp_min_level_db: -70.0
audio_cp_min_syllable_length_s: 0.02
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: position
individuals_sel: Freddy
keypoints_sel: beakTip
s3d_dims_sel: '0'
space_sel: x
trials_sel: 47
