downsample_factor: 100
audio_cp_min_level_db: -70.0
spec_colormap: CET-R4
nc_file_path: C:/Users/FM/Desktop/20250515_01_Ivy/behav/Trial_data.nc
fps_playback: 30.0
audio_cp_min_syllable_length_s: 0.02
percentile_ylim: 99.5
audio_cp_silence_threshold: 0.1
buffer_multiplier: 5.0
downsample_enabled: false
video_path: C:\Users\FM\Desktop\20250515_01_Ivy\2025-05-15_059_Ivy-cam-1.mp4
noise_reduce_enabled: false
apply_changepoint_correction: true
import_labels_nc_data: false
audio_cp_hop_length_ms: 5.0
vmax_db: -20.0
audio_channel_idx: 0
hop_frac: 0.5
window_size: 5.0
all_checkbox_states:
  space: true
nfft: 256
noise_reduce_prop_decrease: 1.0
video_folder: C:/Users/FM/Desktop/20250515_01_Ivy
space_plot_type: space_3D
vmin_db: -120.0
show_changepoints: true
cameras_sel: cam1
cameras_sel_previous: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: aux_velocity
individuals_sel: Ivy
individuals_sel_previous: Freddy
keypoints_sel: beakTip
s3d_dims_sel: '0'
trials_sel: 59
