downsample_factor: 100
audio_cp_hop_length_ms: 5.0
spec_colormap: CET-R4
buffer_multiplier: 5.0
noise_reduce_prop_decrease: 1.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250515_01/behav/Trial_data.nc
window_size: 3.0
import_labels_nc_data: false
nfft: 256
percentile_ylim: 99.5
space_plot_type: Layer controls
audio_cp_min_level_db: -70.0
vmin_db: -120.0
audio_cp_min_syllable_length_s: 0.02
apply_changepoint_correction: true
hop_frac: 0.5
audio_channel_idx: 0
fps_playback: 30.0
audio_cp_silence_threshold: 0.1
noise_reduce_enabled: false
show_changepoints: true
downsample_enabled: false
all_checkbox_states:
  space: true
video_folder: D:/Alice/VidData/20250515_01_Ivy
vmax_db: -20.0
video_path: D:\Alice\VidData\20250515_01_Ivy\2025-05-15_105_Ivy-cam-1.mp4
cameras_sel: cam1
cameras_sel_previous: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: aux_velocity
individuals_sel: Ivy
individuals_sel_previous: Freddy
keypoints_sel: beakTip
s3d_dims_sel: '0'
trials_sel: 105
